services:
  whoscall-app:
    build: .
    ports:
      - "5000:5000"
    image: whoscall-app
    container_name: whoscall-app
    env_file:
      - ".env"
    volumes:
      - ./routes:/routes
      - ./app:/app
      - ./model:/model
      - ./unit_tests:/unit_tests